name: Compile
on: [push]
jobs:
  compile-dissertation-slides:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src/
          root_file: main.tex  # TODO: Replace this with the name of your root file.
          args: -xelatex
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')  # do only if tagged
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload pdf to release assets
        if: startsWith(github.ref, 'refs/tags/v')  # do only if tagged
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/main.pdf  # TODO: Replace this with the desired name of pdf document.
          asset_name: main.pdf  # TODO: Replace this with the desired name of pdf document.
          asset_content_type: application/pdf
